### ISSUE TITLE
A stream nem indul el.

### ISSUE THREAD

**Issue by dtechsrv** [vargalex/plugin.video.rtlmost#7]
A lejátszás problémába ütközik az utolsó verzióval (v2.2.29).

OS: LibreELEC v9.2.8 (Kodi v18.9, Leia),
Eszköz: Mecool KI Pro, Amlogic S905D (GXL).

Beemeltem egy ide vonatkozó részletet a Kodi naplójából:
```
2022-03-29 13:00:12.093 T:3503870848   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xe2 in position 58437: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.rtlmost/default.py", line 54, in <module>
                                                navigator().get_video(url, meta, image)
                                              File "/storage/.kodi/addons/plugin.video.rtlmost/resources/lib/indexers/navigator.py", line 274, in get_video
                                                player.player().play(id, streams, image, meta)
                                              File "/storage/.kodi/addons/plugin.video.rtlmost/resources/lib/modules/player.py", line 81, in play
                                                if is_helper.check_inputstream():
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 407, in check_inputstream
                                                return self._check_drm()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 359, in _check_drm
                                                return self._check_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 329, in _check_widevine
                                                self._update_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 288, in _update_widevine
                                                latest_version = latest_widevine_version()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/widevine.py", line 164, in latest_widevine_version
                                                devices = chromeos_config()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 63, in chromeos_config
                                                return json.loads(http_get(config.CHROMEOS_RECOVERY_URL))
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/utils.py", line 73, in http_get
                                                return content.decode()
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 58437: ordinal not in range(128)
                                            -->End of Python script error report<--
2022-03-29 13:00:12.281 T:4087529472   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.rtlmost/?action=play&url=clip_12932843&meta=%7B%22duration%22%3A+%222555%22%2C+%22plot%22%3A+%22Laci+tov%5Cu00e1bbra+is+a+szob%5Cu00e1j%5Cu00e1ban+rejtegeti+Sacit%2C+mik%5Cu00f6zben+egyre+nehezebben+ker%5Cu00fcli+el+a+lebuk%5Cu00e1st.+Piroska+egy+panasza+nyom%5Cu00e1n+a+Polg%5Cu00e1rmester+%5Cu00fagy+d%5Cu00f6nt%2C+v%5Cu00e9gre+pontot+tesz+a+folyamatban+l%5Cu00e9v%5Cu0151+hivatali+%5Cu00fcgyek+v%5Cu00e9g%5Cu00e9re.+Sv%5Cu00e1b+%5Cu00e9s+Bazs%5Cu00f3+kaszin%5Cu00f3t+nyitnak+Sv%5Cu00e1b+f%5Cu00e9szer%5Cu00e9ben%2C+ahov%5Cu00e1+sz%5Cu00e9p+lassan+a+falu+minden+szenved%5Cu00e9lybeteg+lak%5Cu00f3ja+bet%5Cu00e9ved.%22%2C+%22title%22%3A+%22A+mi+kis+falunk+6.+%5Cu00e9vad+8.+r%5Cu00e9sz%22%7D&image=https://images.6play.fr/v2/images/3669837/raw]
```

Nem tudom, hogy szerver oldalon változtathattak-e valamit, vagy a Widevine CDM lehet-e a problémás.
Bár nem túl sűrűn használom ezt a plugint, de úgy rémlik, hogy pár hete még hibátlanul működött.
_(Akkor azt hiszem, hogy pont egy hiradót néztem meg, és ahhoz elvileg pont kell is a Widevine CDM.)_

**Comment by vargalex** [comment]
Üdv!

Ez inputstream helper hiba, itt olvashatsz róla: https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/495
A 3 napja kiadott [v0.5.9-es release](https://github.com/emilsvennesson/script.module.inputstreamhelper/releases/tag/v0.5.9)-ban javították is...

**Comment by dtechsrv** [comment]
Köszi, meglett. Kodiék a Leia repóját is frissíthenék, mert a Matrix-ban már a 0.5.9 van, de a Leia még nem kapta meg.
Viszont kézzel már felpakoltam és így működik minden. Köszi mégegyszer. ;)
